CREATE DATABASE CheckingTajamar;
GO

USE CheckingTajamar;
GO

CREATE TABLE Absences (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    StudentId INT NOT NULL,
    Subject NVARCHAR(150) NOT NULL,
    Date DATETIME2 NOT NULL,
    Time NVARCHAR(50) NOT NULL
);

CREATE TABLE AttendanceLogs (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    StudentId INT NOT NULL,
    Type NVARCHAR(50) NOT NULL,
    Subject NVARCHAR(150) NOT NULL,
    Date DATETIME2 NOT NULL,
    Time NVARCHAR(50) NOT NULL,
    Minutes INT NULL,
    Text NVARCHAR(250) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE EquiposAutorizados (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    NombreDispositivo NVARCHAR(150) NOT NULL UNIQUE,
    DireccionIP NVARCHAR(50) NOT NULL,
    Activo BIT NOT NULL DEFAULT 1,
    StudentId INT NULL
);

CREATE TABLE Sesiones (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    TipoClase NVARCHAR(50) NOT NULL CHECK (TipoClase IN ('Presencial', 'Casa')),
    Fecha DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CursoId INT NOT NULL,
    PermitirCambioPC BIT NOT NULL DEFAULT 0
);

CREATE TABLE Fichajes (
    Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    StudentId INT NOT NULL,
    FechaHora DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    EquipoId UNIQUEIDENTIFIER NULL,
    Metodo NVARCHAR(50) NOT NULL CHECK (Metodo IN ('Automatico_Alumno', 'Manual_Profesor')),
    IpDetectada NVARCHAR(50) NOT NULL,
    HostnameDetectado NVARCHAR(150) NOT NULL,
    CONSTRAINT FK_Fichajes_Equipos FOREIGN KEY (EquipoId) REFERENCES EquiposAutorizados(Id)
);
